### ISSUE TITLE
Secondary button style

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#10]
There are 5 styles for buttons in Plasma. This is the secondary style.

Each button style has up to 5 states, including as they appear left-to-right below: normal, hover, active, loading and disabled.

---------

**Design:**

![secondary-button](https://cloud.githubusercontent.com/assets/3963512/19160997/17ba5edc-8bc0-11e6-89da-1f9099b51d12.png)

---------

**CSS:**

Hopefully the below will help :) Doesn't cover everything, but does cover off some of the core css for each state.

```
/* Normal */
background-color: $white300;
border: 1px solid darken($white300, 10%);
border-radius: 5px;
height: 38px;
padding: 0 20px;
transition: all 0.2s;
font: $bold5;
color: $weworkblack;

/* Hover */
background-color: darken($white300, 5%);
border-color: darken($white300, 10%);

/* Active */
background-color: darken($white300, 10%);
border-color: darken($white300, 20%);

/* Loading icon */
width: 20px;
height: 20px;
color: #000;
opacity: 0.1;

/* Disabled */
background-color: none;
border-color: #000;
color: #000;
opacity: 0.1;
```

**Comment by nickstamas** [comment]
Done in https://github.com/WeConnect/plasma/pull/44/commits/33586d1e8ec3b89c42554d2b14b50335c69ee1fd
