### ISSUE TITLE
Tertiary button style

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#11]
There are 5 styles for buttons in Plasma. This is the tertiary style.

Each button style has up to 5 states, including as they appear left-to-right below: normal, hover, active, loading and disabled.

---------

**Design:**

![tertiary-button](https://cloud.githubusercontent.com/assets/3963512/19161457/d79331b0-8bc1-11e6-8ca9-ec2eac6cd99d.png)

---------

**CSS (limited):**

```
/* Normal */
background-color: none;
border: 1px solid $weworkblack;
border-radius: 5px;
height: 38px;
padding: 0 20px;
transition: all 0.2s;
font: $bold5;
color: $weworkblack;

/* Hover */
background-color: rgba(0, 0, 0, 0.05);

/* Active */
background-color: rgba(0, 0, 0, 0.1);

/* Loading icon */
width: 20px;
height: 20px;
color: #000;
opacity: 0.1;

/* Disabled */
background-color: none;
border-color: #000;
color: #000;
opacity: 0.1;
```

See also: Tertiary (light) button style (issue #37)

**Comment by nickstamas** [comment]
Done in https://github.com/WeConnect/plasma/pull/44/commits/33586d1e8ec3b89c42554d2b14b50335c69ee1fd
