### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#17]
**Preview:**

<img width="623" alt="screen shot 2016-10-19 at 17 09 14" src="https://cloud.githubusercontent.com/assets/3963512/19537636/bbdf7ab6-961e-11e6-8852-2da051706e21.png">

---------

**CSS (limited):**

_Search CSS largely the same as a text input (see #14).
Additions and differences below:_

**Regular:**

```
/* Textarea */
height: none;
padding: 10px;
(minimum 4 rows)
```

**Large:**

```
/* Textarea */
padding: 15px;
```

**Comment by nickstamas** [comment]
Added in #106
