### ISSUE TITLE
Tabs in a modal

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#41]
_Related to modal issue #25_

-----------

![modal-tabs-preview-1](https://cloud.githubusercontent.com/assets/3963512/24879796/ff8d9fe4-1e05-11e7-8c6a-efffefb8d2ed.png)

![modal-tabs-preview-2](https://cloud.githubusercontent.com/assets/3963512/24879807/047fcfa4-1e06-11e7-80a0-56d88fd75b14.png)

-----------

**CSS:**

```
/* Tabs */
padding: 14px 0 0 14px; /* so first tab aligns with labels */
border-bottom: 1px solid $gray300;

/* Tab */
height: 38px;
padding: 0 15px;
font: $regular2;
color: $weworkblack;
background-color: rgba(255,207,113,0.05); /* $weworkyellow @ 5% opacity) */
border: 1px solid $gray300;

border-radius: 2px 2px 0 0; /* first tab */
border-radius: 0; /* middle tab(s) */
border-radius: 0 2px 0 0; /* last tab */

/* Active tab */
background-color: $white;
border-bottom: 1px solid $white;

/* Hover (non-active tab) */
background-color: rgba(0, 0, 0, 0.02);

/* Focus (non-active tab) */
background-color: rgba(0, 0, 0, 0.05);
```

-----------

**Spec:**

<img width="1358" alt="screen shot 2017-04-10 at 15 58 24" src="https://cloud.githubusercontent.com/assets/3963512/24879849/2be63d12-1e06-11e7-82a3-f97a5f909160.png">

**Comment by kangax** [comment]
Closing via https://github.com/WeConnect/plasma/pull/85
