### ISSUE TITLE
Update to SASS hex colors

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#6]
_Note: These are aren't 'final', but well progressed, and necessary for some further issues coming up related to buttons (issues for those following shortly). Any changes to these colors will be minimal in future though._

Some tweaks to the hex color values (and naming):

![_digital-brand-colors](https://cloud.githubusercontent.com/assets/3963512/19156323/80f9d4c4-8baf-11e6-9eab-f3d5e39ae80d.png)

---------

WeWork Black
`#252729`

Gray 100
`#575757`

Gray 200
`#C2C2C2`

Gray 300
`#E0E0E0`

Gray 400
`#EAEBEC`

Gray 500
`#F4F4F4`

Gray 600
`#FAF9F8`

---------

White
`#FFFFFF`

White 100
`#FFFEF2`

White 200
`#FCF9EB`

White 300
`#ECE9D9`

White 400
`#D7D4C4`

White 500
`#969186`

---------

WeWork Yellow
`#FFCF71`

WeLive Red
`#EF4822`

---------

Link Blue
`#5499C3`

Warning Red
`#D86262`

---------

Purple 100
`#2B3445`

Purple 200
`#59698B`

**Comment by nickstamas** [comment]
Fixed in https://github.com/WeConnect/plasma/commit/aa5cd5845be49a7dcd6628a56810fc4bb6fe0d9b

**Comment by roomfive** [comment]
Woop! ;)
