### ISSUE TITLE
Loading icon (on button)

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#8]
Related to loading state on buttons:

![primary-button](https://cloud.githubusercontent.com/assets/3963512/19159718/7a20b7ce-8bbb-11e6-811e-08cd61f020ae.png)

I was originally recommending the 2nd top-left spinner seen in visual above (code here: http://projects.lukehaas.me/css-loaders/) ...But I wrestled with the code and it was a bitch to edit.

Thinking now to keep it simpler... What do you think of this one?http://codepen.io/roomfive/pen/XjkJmo

Other options I like at: http://tobiasahlin.com/spinkit/

**Comment by nickstamas** [comment]
Added in https://github.com/WeConnect/plasma/commit/ec9b5d94772fa9fc8d1be732466cba2deafc980c
