### ISSUE TITLE
Primary button style

### ISSUE THREAD

**Issue by roomfive** [WeConnect/plasma#9]
There are 5 styles for buttons in Plasma. This is the primary style.

Each button style has up to 5 states, including as they appear left-to-right below: normal, hover, active, loading and disabled.

---------

**Design:**

![primary-button](https://cloud.githubusercontent.com/assets/3963512/19157873/b73481a6-8bb4-11e6-894c-7e6d507e823d.png)

---------

**CSS:**

Hopefully the below will help :) Doesn't cover everything, but does cover off some of the core css for each state.

```
/* Normal */
background-color: $weworkyellow;
border: 1px solid darken($weworkyellow, 15%);
border-radius: 5px;
height: 38px;
padding: 0 20px;
transition: all 0.2s;
font: $bold5;
color: $weworkblack;

/* Hover */
background-color: darken($weworkyellow, 5%);
border-color: darken($weworkyellow, 20%);

/* Active */
background-color: darken($weworkyellow, 10%);
border-color: darken($weworkyellow, 30%);

/* Loading icon */
width: 20px;
height: 20px;
color: #FFF;
opacity: 0.1;

/* Disabled */
background-color: none;
border-color: #000;
color: #000;
opacity: 0.1;
```

**Comment by nickstamas** [comment]
Done in https://github.com/WeConnect/plasma/pull/44/commits/33586d1e8ec3b89c42554d2b14b50335c69ee1fd
